name: 🐍 Gerar animação da cobrinha azul

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite
  workflow_dispatch:     # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  generate:
    name: Gerar e publicar animação
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Dá permissão de escrita para o bot

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha animada
        uses: Platane/snk@v3
        with:
          github_user_name: caiocrdc
          outputs: dist/snake.svg
          palette: "github-dark"  
          color_snake: "68BBD9"  # azul suave da cobrinha
          color_dots: "2d333b,3a6ea5,4ea3e0,68BBD9"  
          # tons:
          # - 2d333b → fundo escuro (cinza padrão GitHub Dark)
          # - 3a6ea5 → azul escuro (poucos commits)
          # - 4ea3e0 → azul intermediário
          # - 68BBD9 → azul claro (muitos commits)

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
