name: 🐍 Gerar animação da cobrinha azul

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:    
  push:
    branches:
      - main

jobs:
  generate:
    name: Gerar e publicar animação
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha animada
        uses: Platane/snk@v3
        with:
          github_user_name: caiocrdc
          outputs: dist/snake.svg
          palette: "github-dark"  
          color_snake: "68BBD9"    
          color_dots: "3b3b3b,8dd3ee,68BBD9,151B23"  

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
